[package]
name = "yadf"
version = "0.1.2"
authors = ["jRimbault <jacques.rimbault@gmail.com>"]
edition = "2018"
description = "Yet Another Dupes Finder"
license = "MIT"
homepage = "https://github.com/jRimbault/yadf"
repository = "https://github.com/jRimbault/yadf"

[[bin]]
name = "yadf"
required-features = ["build-bin"]

[features]
default = ["build-bin"]
build-bin = [
  "structopt",
  "serde_json",
  "seahash",
  "twox-hash",
  "highway"
]

[dependencies]
serde = "1.0.114"
num-format = "0.4.0"
rayon = "1.3.1"
ignore = "0.4.16"
byte-unit = "4.0.8"
structopt = { version = "0.3.15", optional = true }
serde_json = { version = "1.0.57", optional = true }
seahash = { version = "4.0.1", optional = true }
twox-hash = { version = "1.5.0", optional = true }
highway = { version = "0.5.0", optional = true }

[dev-dependencies]
dirs = "3.0.1"
serde_json = "1.0.57"
seahash = "4.0.1"
twox-hash = "1.5.0"
