[package]
name = "yadf"
version = "0.8.3"
authors = ["jRimbault <jacques.rimbault@gmail.com>"]
edition = "2018"
description = "Yet Another Dupes Finder"
license = "MIT"
homepage = "https://github.com/jRimbault/yadf"
repository = "https://github.com/jRimbault/yadf"

[[bin]]
name = "yadf"
required-features = ["build-bin"]

[features]
default = ["build-bin"]
build-bin = [
  "byte-unit",
  "clap-verbosity-flag",
  "csv",
  "env_logger",
  "highway",
  "human-panic",
  "lazy_static",
  "seahash",
  "serde_json",
  "structopt",
  "twox-hash",
]

[dependencies]
# library dependencies
globset = "0.4.6"
ignore = "0.4.16"
log = "0.4.11"
num_cpus = "1.13.0"
rayon = "1.3.1"
regex = "1.4.2"
typed-builder = "0.7.0"
serde = { version = "1.0.114", features = ["derive"] }
# binary dependencies
byte-unit = { version = "4.0.8", default-features = false, optional = true }
clap-verbosity-flag = { version = "0.3.1", optional = true }
csv = { version = "1.1.4", optional = true }
env_logger = { version = "0.8.1", optional = true }
highway = { version = "0.6.2", optional = true }
human-panic = { version = "1.0.3", optional = true }
lazy_static = { version = "1.4.0", optional = true }
seahash = { version = "4.0.1", optional = true }
serde_json = { version = "1.0.57", optional = true }
structopt = { version = "0.3.15", optional = true }
twox-hash = { version = "1.5.0", optional = true }

[dev-dependencies]
assert_cmd = "1.0.1"
dirs = "3.0.1"
serde_json = "1.0.57"
seahash = "4.0.1"
twox-hash = "1.5.0"
predicates = "1.0.5"
rand = "0.7.3"
