[package]
name = "yadf"
version = "0.14.0"
authors = ["jRimbault <jacques.rimbault@gmail.com>"]
edition = "2018"
description = "yet another dupes finder"
license = "MIT"
homepage = "https://github.com/jRimbault/yadf"
repository = "https://github.com/jRimbault/yadf"
readme = "README.md"
categories = ["command-line-utilities", "filesystem"]
keywords = ["dupe", "duplicate", "finder", "fdupes", "fast"]

[[bin]]
name = "yadf"
required-features = ["build-bin"]

[features]
default = ["build-bin"]
build-bin = [
  "ahash",
  "anyhow",
  "atty",
  "byte-unit",
  "clap-verbosity-flag",
  "csv",
  "env_logger",
  "highway",
  "human-panic",
  "metrohash",
  "seahash",
  "serde_json",
  "structopt",
  "twox-hash",
]

[dependencies]
# library dependencies
crossbeam-channel = "0.5.0"
dunce = "1.0.1"
globset = "0.4.6"
grep-cli = "0.1.5"
ignore = "0.4.16"
log = "0.4.11"
num_cpus = "1.13.0"
once_cell = "1.5.2"
rayon = "1.3.1"
regex = "1.4.2"
serde = "1.0.114"
sysinfo = "0.16.0"
typed-builder = "0.9.0"
# binary dependencies
ahash = { version = "0.7.0", optional = true }
anyhow = { version = "1.0.38", optional = true }
atty = { version = "0.2.14", optional = true }
byte-unit = { version = "4.0.8", default-features = false, optional = true }
clap-verbosity-flag = { version = "0.3.1", optional = true }
csv = { version = "1.1.4", optional = true }
env_logger = { version = "0.8.1", optional = true }
highway = { version = "0.6.2", optional = true }
human-panic = { version = "1.0.3", optional = true }
metrohash = { version = "1.0.6", optional = true }
seahash = { version = "4.0.1", optional = true }
serde_json = { version = "1.0.57", optional = true }
structopt = { version = "0.3.15", optional = true }
twox-hash = { version = "1.5.0", optional = true }

[dev-dependencies]
assert_cmd = "1.0.1"
dirs = "3.0.1"
env_logger = "0.8.1"
highway = "0.6.2"
serde_json = "1.0.57"
seahash = "4.0.1"
twox-hash = "1.5.0"
predicates = "1.0.5"
rand = "0.7.3"
