[package]
name = "yadf-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
blake3 = "1.8.5"
libfuzzer-sys = "0.4"
tempfile = "3"
yadf = { path = "..", default-features = false }

[[bin]]
name = "scan"
path = "fuzz_targets/scan.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
