name: CI

on:
  push:
    paths-ignore:
      - "**.md"
    branches-ignore:
      - "try/**"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    # At 13:23 on day-of-month 23.
    - cron: "23 13 23 * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, 1.88.0]
        feature_set: ["--no-default-features", "--all-features"]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: ./.github/actions/cargo-cache
        with:
          prefix: check-${{ matrix.rust }}
      - name: Run build check
        run: cargo check ${{ matrix.feature_set }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: ./.github/actions/cargo-cache
        with:
          prefix: clippy
      - name: Run cargo clippy
        run: cargo clippy --all-features -- -D warnings

  format:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  tests:
    name: Tests
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: ./.github/actions/cargo-cache
        with:
          prefix: tests-${{ matrix.rust }}
      - name: Build tests
        run: cargo build --tests
      - name: Run tests
        run: cargo test --all-features
